### ISSUE TITLE
MS 1st Party Apps are available in the report.

### ISSUE THREAD

**Issue by MugundGH** [cparker-msft/appImpersonationUsersReport#1]
In the export, could see the 1st Party Apps available in the report. Can this be removed so that we have the exact inventory of the apps that are originally impacted.

00000003-0000-0000-c000-000000000000
00000002-0000-0ff1-ce00-000000000000
13937bba-652e-4c46-b222-3003f4d1ff97
a3883eba-fbe9-48bd-9ed3-dca3e0e84250

All above are internal apps to MS, but they are available in the export from the script output.

**Comment by cparker-msft** [comment]
@MugundGH I've updated the script. Please try again and confirm if you're no longer seeing the 1P apps in the report.

**Comment by cparker-msft** [comment]
Following up on this @MugundGH , is the script now working as expected for you?

**Comment by MugundGH** [comment]
Hello @cparker-msft ,

Now we could see that the First party app arent appearing in the report. However since we have more than 100k users in our infra, we are not even able to run this report for more than a hours time beyond which its timing out. Can there be any enhancements that can be targetted for the large user base??

**Comment by cparker-msft** [comment]
@MugundGH that is unfortunately a limitation of the underlying Search-UnifiedAudit log cmdlet used to perform the search. The script allows for the search window parameters to be tweaked (e.g.: reduce search window) which may help, or you may have better results by performing the search in the [Microsoft Purview Audit portal](https://learn.microsoft.com/en-us/purview/audit-search?tabs=microsoft-purview-portal) (albeit without the additional functionality provided by the script).

Thank you for confirming that the 1P apps no longer appear in the report. Will go ahead and close this issue as resolved.
